version: '3'

services:
  web-app:
    build: ./web-app
    ports:
      - '80:3000'

  bio-engine:
    build: ./bio-engine
    ports:
      - '7000:7000'
    # TODO: remove once aliases used properly
    network_mode: 'host'

  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - './db_data:/data/db'

